### ISSUE TITLE
How to view documentation old version ?

### ISSUE THREAD

**Issue by tuananhzippy** [edge-js/edge#103]
I am using AdonisJS version 4.1. At this version is used 1.1.4. Now that the tutorial has been updated to the new version, I have no way of seeing the old tutorials for AdonisJS 4.1 using Edge Template.

**Comment by aqilfiqran** [comment]
You can check [this](https://legacy.adonisjs.com/docs/4.1/)

AdonisJs version 4.1 documentation has migrated to legacy adonis. So if you type "adonisjc documentation". It just show new version AdonisJs

**Comment by faizananwerali** [comment]
links are not working.

![image](https://user-images.githubusercontent.com/12691366/147217198-e8acfd38-e7ec-43e3-92b1-6cdc7eb6bdeb.png)

![image](https://user-images.githubusercontent.com/12691366/147217052-ea995ceb-14e3-4aed-8a09-8311cfa237eb.png)

![image](https://user-images.githubusercontent.com/12691366/147217463-fbabaec7-da77-491c-8fde-46858c8b53b9.png)

These links are dead for old documentation.

Can you please provide links, so we can view old information.

Dead links:
[https://edge.adonisjs.com/docs/globals](https://edge.adonisjs.com/docs/globals)
[https://edge.adonisjs.com/docs/syntax-guide](https://edge.adonisjs.com/docs/syntax-guide)
[https://edge.adonisjs.com/docs/tags](https://edge.adonisjs.com/docs/tags)
