### ISSUE TITLE
Links are dead in legacy documentation

### ISSUE THREAD

**Issue by faizananwerali** [edge-js/edge#108]
Links are not working in Legacy Documentation [https://legacy.adonisjs.com/docs/4.1/views#_templating](https://legacy.adonisjs.com/docs/4.1/views#_templating)

![image](https://user-images.githubusercontent.com/12691366/147217198-e8acfd38-e7ec-43e3-92b1-6cdc7eb6bdeb.png)

![image](https://user-images.githubusercontent.com/12691366/147217052-ea995ceb-14e3-4aed-8a09-8311cfa237eb.png)

![image](https://user-images.githubusercontent.com/12691366/147217463-fbabaec7-da77-491c-8fde-46858c8b53b9.png)

These links are dead for old documentation.

Can you please provide links, so we can view old information.

Dead links:
[https://edge.adonisjs.com/docs/globals](https://edge.adonisjs.com/docs/globals)
[https://edge.adonisjs.com/docs/syntax-guide](https://edge.adonisjs.com/docs/syntax-guide)
[https://edge.adonisjs.com/docs/tags](https://edge.adonisjs.com/docs/tags)
[https://edge.adonisjs.com/docs/iteration](https://edge.adonisjs.com/docs/iteration)

**Comment by thetutlage** [comment]
Locking as I no interest in dealing with people who lack empathy
