### ISSUE TITLE
@if (condition) vs. @if(condition)

### ISSUE THREAD

**Issue by assertchris** [edge-js/edge#11]
If you put a space between `@if` and the condition parens, you get `E_INVALID_EXPRESSION`, which seems like a strange restriction. I looked through this repo but didn't see a place where I could suggest patching to allow for the space (assuming you think it's even a good change to make)...

**Comment by macOneOone** [comment]
I've the same issue
<img width="1330" alt="captura de ecra 2018-03-13 as 17 38 53" src="https://user-images.githubusercontent.com/16170629/37356076-737d98e4-26e5-11e8-945a-000c6c77e7c7.png">

**Comment by thetutlage** [comment]
Yes, the tags parser doesn't allow spaces in between. Actually edge needs some love at parse level, I will start working on it soon. ( busy with other stuff )

**Comment by thetutlage** [comment]
Fixed in `v3.0.0`. It has breaking changes and will be out by end of the week
