### ISSUE TITLE
Condition in one line

### ISSUE THREAD

**Issue by DZ8540** [edge-js/edge#113]
Conditions don't work in one line 

Example: 
```blade
<input type="email" class="form-control @if(err) is-invalid @endif" name="email" placeholder="hello@example.com">
```

**Comment by RomainLanz** [comment]
Hey @DZ8540! 👋🏻 

Use a ternary instead.

```
{{ err ? 'is_invalid' : '' }}
```

**Comment by DZ8540** [comment]
Hello, thanks, cool, but it would be even cooler if we added the ability to write conditions in this way in one line :)
