### ISSUE TITLE
Is it possible to perform a static analysis of the template Edge.js ?

### ISSUE THREAD

**Issue by monochromer** [edge-js/edge#123]
I need to get a list of all template dependencies - layout, components, includes, etc.

This is important for two reasons:
- it is necessary to include styles to the page only of those components that are declared in the template.
- in static site build systems (gulp) in development mode, you need to rebuild only those pages whose components have changed.

As an example, in the Pug template engine, after compilation, the `dependencies` property appears in the HTML render function.

**Comment by thetutlage** [comment]
So, are you only looking for dependencies on other templates only? As you mentioned `layout`, `components`, `includes` and so on?

I am not much aware with pug, but if it has runtime components or includes, how do you manage those? For example: In AdonisJS, you can do

```
@include(user.isAdmin ? 'partials/admin' : 'partials/user')
```

And many times, the partial path can be a variable to

```
@include(getPartialFor(user))
```

**Comment by thetutlage** [comment]
> Yes. But it was useful in the future to get information about html tags link, script, img, etc.

Edge can be written inside any markup language, be it HTML, Markdown, JSON, or YAML. So we never parse HTML at all.

> I will try to avoid them ) .Pug doesn't support runtime includes and layout extends. But [Nunjucks Parser](https://github.com/chocolateboy/nunjucks-parser) uses https://github.com/chocolateboy/parcel-plugin-nunjucks/issues/1#issuecomment-423495829.

Yeah, maybe the return value can express that a runtime expression was used for the path. 

I am not sure if I am work on it right now (looking at my workload). You can contribute and I will try my best to be available to answer your queries and maybe tweak the APIs a little (if required)

**Comment by thetutlage** [comment]
Closing since not actionable
