### ISSUE TITLE
Just a silly question

### ISSUE THREAD

**Issue by mushketer888** [edge-js/edge#124]
Hello all!
Is it possible to format .edge with prettier (or with something else)?

Thanks!

**Comment by mushketer888** [comment]
Onlu this works [https://github.com/Julien-R44/adonis-vscode-extension](https://github.com/Julien-R44/adonis-vscode-extension)

**Comment by JannieT** [comment]
It would be great if we could use Prettier with all its richness, configurability and plugins (tailwind especially).
