### ISSUE TITLE
Passing values from edge to alpine.js (Question)

### ISSUE THREAD

**Issue by tianjos** [edge-js/edge#134]
There is something like tag template that I can pass values from edge template to alpine components?

Right now I have to do something like this:
`<div x-data={alpineComponent('{{ edgeValue }}')}></div> --> cumbersome?`

I need to evaluate the things to work

**Comment by yahya-abou-imran** [comment]
I don’t see how it wouldn’t work, could you indicate what is the output or the error?  
Also, from where `alpineComponent` is coming from?

**Comment by tianjos** [comment]
It Works correctly, I personally think that syntax is cumbersome. My question was about some alternative syntax existence

About the alpine component, it is a regular alpine component registered on Alpine.data
