### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by StepanMynarik** [edge-js/edge#145]
### Package version

6.0.0-10

### Describe the bug

I wanted to make a "Future Request" instead of a bug report, but it's not working. So that is a bug report right there 😆 

However the original topic I wished to discuss is **the name of this project**.

I'm so glad I found it! But it was at the very last moment, after lots and lots of research on templating engines (EJS, Handlebars, Nunjucks, ETA and many others).

Seeing "Edge" just reminds me of the browser.

And when I finally discovered Edge the templating engine, it was tougher to find VSCode extensions on marketplace for it, since just putting "Edge js" or something isn't enough.
Also searching for the package and it's plugins on npm is not very pleasant. First results for "Edge js" always lead to https://www.npmjs.com/package/edge-js and others.
At first edge js templating engine wasn't even on the first page for me.

This is just a suggestion. Edge is amazing for my use case so I just wanted to chip in a little bit with my feedback (also posted a review on the "fresh from the oven" VSCode extension).

**Comment by thetutlage** [comment]
Hello @StepanMynarik 

Yeah, I know Edge is not one of the best names regarding discoverability. For now, I think we will have to live with it. Changing the project name will require a lot of communication with existing users, and I would love to avoid it for now.
