### ISSUE TITLE
Can not use @ symbol in template files

### ISSUE THREAD

**Issue by SerdarSanri** [edge-js/edge#146]
### Package version

5.5.1

### Describe the bug

While using @ symbol either for email address or other parts of the context, Webstorm complains it is an Edge error. I tried to escape with backslash but didn't make any difference. 

![image](https://github.com/edge-js/edge/assets/651202/06b59f69-6593-47b9-b1dc-4075c97c3042)

![image](https://github.com/edge-js/edge/assets/651202/862ba589-ce20-4beb-92df-8d56a530c924)

**Comment by thetutlage** [comment]
Hello, what syntax highlighter are you using for Edge? We do not have an official one for WebStorm.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
