### ISSUE TITLE
Question: What is the difference between partial and component?

### ISSUE THREAD

**Issue by sinh117801** [edge-js/edge#150]
### Package version

6.0.1

### Describe the bug

I read through the document several time on Edge docs, but I'm still not get the key difference between partial and component.

**Comment by sinh117801** [comment]
Correct me if I'm wrong. What I understand here, partial is for block of template that don't have it own props but can have it own state. Opposite from partial, component is for block of template that relies on props and state for value, but cannot access value from its parent.

**Comment by thetutlage** [comment]
Partials have access to the state of the parent template and they do not accept props or slots.

Components accepts props and slots and cannot access parent template state. 

You can learn more about Edge on Adocasts. https://adocasts.com/series/lets-learn-adonisjs-6/lessons/edgejs-templating-basics. They use AdonisJS in the videos, but the Edge knowledge still applies to projects using Edge without AdonisJS
