### ISSUE TITLE
Creating new feature request does not seem to be possible

### ISSUE THREAD

**Issue by lorefnon** [edge-js/edge#152]
### Package version

N/A

### Describe the bug

Hello thanks for open-sourcing and maintaining edge. There seems to be some misconfiguration with github issue template chooser. 

When we try to create a new feature request, the button takes us back to the issue type chooser making it impossible to move forward

https://github.com/edge-js/edge/assets/1449492/84d0ffd0-a8d0-4432-9721-c16f05a979f3

**Comment by Julien-R44** [comment]
Thanks [it should be fixed now](https://github.com/edge-js/.github/commit/370bb2b72480e2cba6c3db0c6939f7bd1a749d2f). Feel free to re-open if issue persist

**Comment by lorefnon** [comment]
Thank you.
