### ISSUE TITLE
Discussion for a new feature - Globally disable html escaping

### ISSUE THREAD

**Issue by lorefnon** [edge-js/edge#153]
Hello, I am planning to use edge for a code-generator. 

The default behaviour of html escaping does not make sense for this use case and therefore I wanted to propose that we have an option that can be passed to `Edge.create` to disable this. Any alternate way to substitute the default escaper with a noop implementation would also be alright. 

I hope this would be acceptable since edge claims to not be tied to HTML: 

> It is not tied to any DOM implementation. Edge is not even tied to HTML.

**Comment by sausawmg** [comment]
I use the escape function from Bun to replace the one in Edge.
`edge.globals.html.escape = Bun.escapeHTML;
`

A noop version of this would be
`edge.globals.html.escape = (s) => s;`

**Comment by sausaw** [comment]
@lorefnon  I use the escape function from Bun to replace the one in Edge.
`edge.globals.html.escape = Bun.escapeHTML; 
`
A noop version of this would be
`edge.globals.html.escape = (s) => s;`
