### ISSUE TITLE
Creating a syntax highlighter for nvim

### ISSUE THREAD

**Issue by Kenzo-Wada** [edge-js/edge#157]
Hi Edge Team, 

I was reading docs and noticed that .edge syntax highlight is not still supported for nvim.
I'd like to create a tree-sitter by using [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter), is it OK?

**Comment by thetutlage** [comment]
Sure, that will be a great addition. Lemme know if you need any help understanding the Edge syntax, though this guide should cover the most of it for you. https://edgejs.dev/docs/syntax_specification

**Comment by Kenzo-Wada** [comment]
TY! I'll get started!
