### ISSUE TITLE
Get value of object with 2 variables

### ISSUE THREAD

**Issue by garcia-marco** [edge-js/edge#21]
Hello i'm trying to do something like this :

`<input value="{{object1[object2.id]}}">`

But I can't find a solution. Is this even possible ?

**Comment by RomainLanz** [comment]
Hey @garciamarco33! 👋 

Do you have any error while running your code?

**Comment by garciamarco33** [comment]
Yes, 
`E_INVALID_EXPRESSION: Invalid expression <object1[object2.id]>`

**Comment by thetutlage** [comment]
Yeah seems like a bug, since it has nested [Member expressions](http://esprima.org/demo/parse.html?code=object1%5Bobject2.id%5D) and somewhere in the code it's not handled properly.

Lemme look into it and see if it's a easy fix

**Comment by garciamarco33** [comment]
Nice,
thank you !

**Comment by thetutlage** [comment]
Fixed and published as `1.1.4`

**Comment by garciamarco33** [comment]
Working great, thanks !

**Comment by garciamarco33** [comment]
Hello again,
didn't touch the branch where I put this since the 26 and when I tried to test it today, the same error popped again : 
`E_INVALID_EXPRESSION: Invalid expression < object1[object2.id] >`
Nothing have changed i'm confused...
Don't you know something ?

**Comment by garciamarco33** [comment]
I checked more in detail, 
`value="{{ object1[object2.id] }}"` is not working, I don't know why it worked for a bit,
did you try it ?
If I put `value="{{object1}}"` or `value="{{object2}}"` and it's working so it's not the variables.

**Comment by thetutlage** [comment]
Are you sure, you are using the latest release `1.1.4`

**Comment by garciamarco33** [comment]
Yup,
I've done `npm i edge.js@1.1.4` to make sure of it

**Comment by thetutlage** [comment]
Fixed in `v3.0.0`. It has breaking changes and will be out by end of the week
