### ISSUE TITLE
Issue when use symbols `` in template

### ISSUE THREAD

**Issue by PazzaVlad** [edge-js/edge#23]
If Edge template has ES6 template literals it broke rendering

For example:

file.edge:
```js
...
@raw
`ok`
@endra
...
```

or

```js
...
`ok`
...
```

Will throw en error:

![mxdfkdi](https://user-images.githubusercontent.com/7755205/35912146-65ada412-0c04-11e8-829a-38ef9a0960bc.png)

**Comment by thetutlage** [comment]
Edge converts your template to a Javascript function, and back ticks are valid javascript expression, so they together mangle.

I agree the behavior can be fixed, but I have to make bunch of changes to edge ( performance improvements ), then I will fix it.

For now you can escape the back ticks.

```
@raw
\`ok\`
@endra
```

**Comment by PazzaVlad** [comment]
Thanks for reply, with escaping it works perfectly. 

Definitely performance improvements much more important then this rare (in real life) case :)

**Comment by thetutlage** [comment]
Yeah more than that, I will be making bunch of changes ( which will include this too ) at once. I need time for that, so completing pending work till then

**Comment by thetutlage** [comment]
Fixed in `v3.0.0`. It has breaking changes and will be out by end of the week
