### ISSUE TITLE
Tag to set default values

### ISSUE THREAD

**Issue by alinnert** [edge-js/edge#37]
Is there a way to set the value of a variable if it is not set already? I think I could use something like:

~~~
@unless(optionalVar)
    @set('optionalVar', 'default value')
@endunless
~~~

But that's pretty much code. Something like this would be better:

~~~
@setDefault('optionalVar', 'default value')
~~~

This would be very useful in components. The documentation mentions that one could write their own tags. But it just points to a video that does not exist.

**Comment by bstoots** [comment]
This would be a helpful feature for sure.  I would also like to see the documentation for adding custom tags added.

**Comment by thetutlage** [comment]
Can you share how exactly you expect the `setDefault` to work?

Should it just check for `undefined` values or any value that is non existing. By non existing values, I mean `empty strings`, `false booleans`, and `null`

**Comment by bstoots** [comment]
I can't speak for @alinnert but in my opinion the two examples originally posted by @alinnert should behave exactly the same. The second simply acting as a sort of short-hand notation.

Separately, if some docs or examples could be written for adding custom tags that would be helpful.  I just noticed the Edge docs still reference a nonexistent video here: https://edge.adonisjs.com/docs/tags#_writing_your_own_tags.
