### ISSUE TITLE
[Question] Custom template extensions

### ISSUE THREAD

**Issue by samuelthompson189** [edge-js/edge#40]
Hi, is it possible to use a custom file extension such as `.html` or `.edge.html`?

**Comment by thetutlage** [comment]
Any specific reason you are looking for this?

**Comment by samuelthompson189** [comment]
Yes, I am currently working on a project where `html` files are already being used by our users. It would nice to be able to turn them into edge templates without renaming all of the files. I am also interested writing an implementation that uses markdown as well as html (`.edge.md`).

**Comment by klawdyo** [comment]
Does it means that is not possible?

My APP in vue is a SPA and i want generate its code to include some meta-tags. In this case, i want run index.html with edge variables inside.

**Comment by thetutlage** [comment]
Nope. Not possible. I don't see how keeping extension to `.edge` prevents with all these use cases
