### ISSUE TITLE
@section and @component tags behaviour

### ISSUE THREAD

**Issue by queiroz** [edge-js/edge#42]
I’ve noticed that when you use a `@section` tag inside a  `@component` the component throws an error!

I would like to decouple things and probably re-use the sections defined in the `@layout('layouts.master')` inside a `@component`.

For instance, I have a `@!section('extra_js')` which is right at the bottom of the `@layout('layouts.master')` and within the `@component`, I would like to add JS dependencies that are only related to the component itself and to be loaded only when that component is in use.

e.g.

```
- master.edge

<html>
  ...
  <body>
    @!section('header')

   <main>
      @!section('content')
   </main>
   
   <footer>
       @!section('footer')
   </footer>

   {{-- extra js --}}
   @!section('extra_js')

  </body>
</html>

- home.edge

@section('header')
  @!component('components.header', type = 'header', title = title, description = description)
@endsection

- components/header.edge

<header id="{{ type }}">
    ...
</header>

@section('extra_js')
<script type="text/javascript" src="{{ appUrl('js/vendor/file.min.js') }}"></script>
@endsection

```

Another thing that I’ve noticed is that when you try to re-use a @section within a @section itself it doesn’t include the code where is supposed to be.

e.g.

```
- master.edge
@!section('content')
@!section('bottom')

- home.edge
@section('content')
    <h1>Welcome</h1>
    @section('bottom')
         <p>some other text</p>
    @endsection
@endsection
```

the code from the nested section is included within the `@section('content')` rather than `@section('bottom')`

**Comment by thetutlage** [comment]
Nested sections are not supported and they will never be.
