### ISSUE TITLE
Unable to concatenate strings into @include

### ISSUE THREAD

**Issue by danilopolani** [edge-js/edge#46]
At this time, I'm unable to do this: `@include('my-folder.' + someVariable)` because it will throw: `InvalidExpressionException: E_INVALID_EXPRESSION: Invalid expression <'my-folder.' + someVariable> passed to (include) block ` and the only way to achieve this is doing a long if/elseif which is really ugly.

I suppose the problem is also for other tags, but I haven't tested it with them.

**Comment by thetutlage** [comment]
Fixed in `v3.0.0`. It has breaking changes and will be out by end of the week.

You will be able to use template literals after that

```
@include(`my-folder.${someVariable}`)
```
