### ISSUE TITLE
[feature] Allow for the presenter logic to be written inside edge files

### ISSUE THREAD

**Issue by hadihallak** [edge-js/edge#49]
**it would be nice to be able to work with the data at the component level instead on a separate presenter file**
such feature will allow for writing a much easier/cleaner component based applications where the component holds all of the html and the logic that drives it in one place.

```js
@presenter
  // presenter block will have the same scope to the file it lives in
  // so in the case of components it will only have access to props and to the global variables 
  // where on a normal edge file it will have access to everything that gets passed to it
@endpresenter

// html/edge syntax goes here...
```

by making it inside a presenter block we avoid confusing it with the script tag for new-comers and they will be able to tell which is which.

**Comment by thetutlage** [comment]
Sorry for getting a bit late on this. 

Using `@presenter` tag will not work out of the box, since the Presenter must be known before executing the compiled template and the tags are evaluated at runtime.

Flow looks like this 
<img width="200" alt="screen shot 2018-06-01 at 1 08 43 pm" src="https://user-images.githubusercontent.com/1706381/40827974-f397446c-659c-11e8-8bdb-6fde9a8320ea.png">

Another option is to have Vue style template files.

```
<template>
 Your HTML
</template>

<style>
</style>

<presenter>
 class UserPresenter {
 }

 module.exports = UserPresenter
</presenter>
```

Couple of things to note.

1. The client Javascript cannot be written inside the `presenter` block.
2. The `style` will work as `cssinjs` specs. Since Edge is a simple server template engine, I have no plans to add webpack support to compile a server template and allow 30 ways to write css.

**Comment by hadihallak** [comment]
Thanks for the flow chart... 
Also with the addition of `cssinjs` it makes a lot of sense to have a vue like template file

**As to your notes:**
> The client Javascript cannot be written inside the presenter block.

I think that since we're not gonna use the script tag then this shouldn't confuse anyone but regardless, it wouldn't hurt to mention it in the docs for newcomers, just in case.

> The style will work as cssinjs specs. Since Edge is a simple server template engine, I have no plans to add webpack support to compile a server template and allow 30 ways to write css.

This is very reasonable... i agree... edge does it job well as server side templating engine and if someone needs a bazillion ways to write css then he's most likely making a spa which isn't the purpose of a server side templating engine.

I really believe that Edge is in a sweet-spot right now.. where it's easy to use and remember the syntax but also powerful specially with the addition of features such as `template literals`, `cssinjs` and hopefully, `presenter` logic inside edge files.

**Comment by thetutlage** [comment]
The `v3` has removed presenters completely for the edge templates and this is done to improve the errors debugging.

## More info

Earlier edge was using a runtime method called `ctx.resolve` to resolve the value of a variable at runtime and used to hop between multiple places to find the value. For example:

- Look for value inside the template state
- Fallback to presenter properties
- Fallback to globals

However, if a Syntax error exception was raised during `ctx.resolve`, the end user used to see unhelpful error message. For example:

The template has following snippet

```
{{ username.toUpperCase() }}
```

It will be compiled down to

```
ctx.resolve('username').toUpperCase()
```

Let's imagine the `username` is an object and not a string. The error raise by Javascript runtime will be

```
TypeError: resolve(...).toUpperCase is not a function
```

Now, the end user has no idea what `resolve` is.

The above scenario is a very simple example. In some cases, it gets even uglier.

## Conclusion
I know, that Presenters were helpful, but the downside of seeing cryptic messages weighs the upsides of Presenters. There are many smart ways to work around with Presenters, but not much to overcome the cryptic errors.

Happy to discuss more :)
