### ISSUE TITLE
how to use console.log inside .edge file

### ISSUE THREAD

**Issue by Ali-Azmoud** [edge-js/edge#54]
Hi

When I use ` {{ console.log( variable ) }} ` inside `.edge` file, I get the following error:

    this.context.resolve(...).log is not a function

How to use console.log or any raw javascript statement inside .edge file?

**Comment by anhnt** [comment]
try this 

```
edge.global('debug', function (o) {
    console.log(o);
    return o.toString();
})

**Comment by anhnt** [comment]
then in template

```
<pre>{{ debug(yourObj )}}</pre>
