### ISSUE TITLE
@if inside a html 'option' 

### ISSUE THREAD

**Issue by limonazzo** [edge-js/edge#62]
I’ve noticed that when you use a `@if` tag inside a html `option` does't work.
e.g.

```
<select name="seccion" >
    <option @if( seccion == 'algo' ) selected @endif value="algo">Algo</option>
</select>

```
thows in html: 

```
<option @if(="" .seccion="=" 'algo'="" )="" selected="" @endif="" value="algo">algo</option>
```

I had to do this :

```
@if( seccion == 'algo' )
<option selected value="algo">algo</option>
@else
<option value="algo">algo</option>
@endif
```

I'm not sure if it's correct; tanks anyway. (Y) 

Node v10.15.1
Adonis 4.1

**Comment by thetutlage** [comment]
Tags are block level definitions and cannot be mixed with other contents. Sorry, this is how parser works and cannot be changed, however, you can use ternary operator for same.

```
<option {{ section === 'algo' ? selected : '' }} value="algo">Algo</option>
```
