### ISSUE TITLE
Custom tag example

### ISSUE THREAD

**Issue by ghost** [edge-js/edge#65]
How to add a custom tag? Example:

```
@mytag
   <!-- code -->
@endmytag
```

**Comment by anhnt** [comment]
+1

**Comment by harlley** [comment]
+1

**Comment by RomainLanz** [comment]
Hey all, 👋 

Documentation will be improve!
In the meanwhile, you can check [this code](https://github.com/RomainLanz/adonis-guard/blob/develop/src/ViewBindings/Can.js) as an example.

Feel free to ask any question in the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6).
