### ISSUE TITLE
@set value default value and update value

### ISSUE THREAD

**Issue by rinXer7** [edge-js/edge#66]
Hello. I'm using Gulp for compiling Edge files to HTML. My file structure:

/src/edge/Base/config.edge
/src/edge/Base/head.edge
/src/edge/Base/layout.edge
/src/edge/index.edge

I include config.edge in layout.edge, I include head.edge in layout.edge between <head> tags.
I declare variables with @set key. But I can't use and update variables in index.edge.

*My English not so good. Forgive me, if I did something wrong.*

**Comment by thetutlage** [comment]
Bit late to issue and not sure, if you are still facing the problem. Closing the issue for now, but feel free to re-open it
