### ISSUE TITLE
Better documentation for Components

### ISSUE THREAD

**Issue by xaddict** [edge-js/edge#68]
## Why this feature is required (specific use-cases will be appreciated)?
Right now there's just a video which is not easily scannable and I don't believe it touches on all the details. Also, it is based on an older version of Edge since it doesn't use objects in the tag

## Have you tried any other work arounds?
The video is a tiny thumbs up

## Are you willing to work on it with little guidance?
I could write the whole page, but I'll need more information on everything that @component does

**Comment by thetutlage** [comment]
@xaddict I am planning a major release by the end of this week. Do you think, you will be able to help the requirements you have for the components docs?
