### ISSUE TITLE
Can't break the line when there's a parenthesis expression in the last value of an object or an array

### ISSUE THREAD

**Issue by emanuel15** [edge-js/edge#69]
## Package version
1.1.4

## Node.js and npm version
Node v10.15.3
npm 6.9.0

## Sample Code (to reproduce the issue)
Suppose you have a component `comp.edge`, with any code inside, le'ts just print a variable:
```{{ x }}```

If you break the last line after a closing `)`, Edge throws an InvalidExpression error.

Doesn't work:
```
@!component('comp', {
    x: [
        (1 + 2)
    ]
})

@!component('comp', {
    x: [
        lowerCase('A')
    ]
})

@!component('comp', {
    x: (1 + 2)
})

@!component('comp', {
    x: lowerCase('A')
})
```
Works:
```
@!component('comp', {
    x: [
        (1 + 2)]
})

@!component('comp', {
    x: [
        lowerCase('A')]
})

@!component('comp', {
    x: (1 + 2)})

@!component('comp', {
    x: lowerCase('A')})

@!component('comp', {
    x: [
        (1 + 2
    )]
})

@!component('comp', {
    x: [
        lowerCase('A'
    )]
})

@!component('comp', {
    x: (1 + 2
)})

@!component('comp', {
    x: lowerCase('A'
)})

@!component('comp', {
    x: lowerCase('A'
)})
```
As you can see, functions get affected as well and the problem also occurs in arrays values.
The `key = value` syntax has the same problem.

**Comment by thetutlage** [comment]
Fixed in `v3.0.0`. It has breaking changes and will be out by end of the week
