### ISSUE TITLE
style tag doesnt work with google fonts

### ISSUE THREAD

**Issue by kswope** [edge-js/edge#70]
```
{{ style('https://fonts.googleapis.com/css?family=Open+Sans') }}
```

generates this
```
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans.css" />
```

Google doesn't like ".css" at the end, as demonstrated below:
[Generated](https://fonts.googleapis.com/css?family=Open+Sans.css)
[Fixed by hand](https://fonts.googleapis.com/css?family=Open+Sans)

**Comment by kswope** [comment]
I should point out that theres a work around, as the adonis starter shows

At the top of the style.css file
```
@import url('https://fonts.googleapis.com/css?family=Montserrat:300');
```

**Comment by thetutlage** [comment]
Why not use the HTML directly?

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans" />
```

**Comment by kswope** [comment]
Arguably why have style helper at all?  Just use assetsUrl() helper.  

It doesn't seem like appending css to the end contributes anything but confusion.

**Comment by thetutlage** [comment]
The `style` helper was wasn’t created by considering all possible use cases.

Do you think you can help with how to detect different url styles and then append or not append `.css`?

**Comment by thetutlage** [comment]
The `style` is planned for removal in the future version
