### ISSUE TITLE
edge.global not a function error

### ISSUE THREAD

**Issue by EriecTanijaya** [edge-js/edge#72]
it say edge.global is not function, any workaroud?
`app.use('*', (req, res, next) => {
  edge.global('auth', req.session.userId)
  next();
});`

**Comment by thetutlage** [comment]
Bit late to the issue and not sure if you are still facing this problem. Feel free to reopen the issue

**Comment by arijitdatta** [comment]
@thetutlage  I am still facing the issue. Can you please reopen it.

**Comment by adi2420** [comment]
@thetutlage I have the same error, can you help me with it.
I'm looking for the solution everywhere but cannot find it

**Comment by thetutlage** [comment]
@thetutlage Please share the version of edge you are using and the code you have written

**Comment by saurabh23401** [comment]
Hello , Did anyone get the fix , Im also getting same 

Version "edge.js": "^5.3.2",

TypeError: edge.GLOBALS is not a function
for below code .

const edge = require('edge.js')
app.use('*', (req, res, next) => {
    edge.GLOBALS('auth', req.session.userId)
    next()
});

**Comment by saurabh23401** [comment]
There is workaround for the issue , may be helpful.


just in case if you using aysnc & await need to refersh the page to see the effect :)


app.use('*', (req, res, next) => {
   app.locals.auth =  req.session.userId
    next();
  
}); // > adding login page for Guest

**Comment by Once-Man** [comment]
how to solve TypeError: edge.global is not a function

**Comment by JOE-JOE-NGIGI** [comment]
I'm also facing this issue. Please assist to resolve.
Here is my code:
```
const edge = require("edge.js");

app.use('*', async (req, res, next) => {
    const { userId } = req.session;
    if (userId) {
        const user = await User.findById(userId);
        edge.global("user", user);
        edge.global("userId", req.session.userId);
    }

    next();

});
```

Error:

 edge.global("user", user);
             ^

TypeError: edge.global is not a function
    at C:\learning_node_js\nodeblog\app.js:52:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Julien-R44** [comment]
```ts
const { default: edge }= require("edge.js");

edge.global(...)
```
