### ISSUE TITLE
Missing docs for `elIf`

### ISSUE THREAD

**Issue by fians** [edge-js/edge#73]
It seems on the [docs for Globals](https://edge.adonisjs.com/docs/globals), there is no docs for `elIf`. Where is the docs repo located? I want to make pull request on it to add the docs for `elIf` if that possible.

Thanks.

**Comment by techtuxbr** [comment]
Yes, I can't find docs about it.

**Comment by thetutlage** [comment]
The `elIf` is removed in the next version and hence there is no need for its docs.
