### ISSUE TITLE
component cannot have variable for template name

### ISSUE THREAD

**Issue by joezg** [edge-js/edge#76]
Please see this contrived example:

@set("template", "path.to.tamplete") 
@!component(template) 

throws
E_MISSING_VIEW: Cannot render .edge. Make sure the file exists at...

and
@set("template", "path.to.tamplete") 
@!component(template, {})

throws
E_CANNOT_PARSE: RuntimeException: E_CANNOT_PARSE: RuntimeException: E_CANNOT_PARSE: Error: Cannot parse ThisExpression expression Report to the package author Report to the package author Report to the package author

If tag is changed from component to include, this example work.

Is it possible to fix this? It seems to me that dynamically setting a component is common use case and one that I really need.

**Comment by thetutlage** [comment]
Can you share which version of Edge you are using?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter

**Comment by djyde** [comment]
`"edge.js": "^1.1.4"` not works

**Comment by RomainLanz** [comment]
Please, create a new issue with a minimum amount of code to reproduce your problem instead of bumping an old one.
