### ISSUE TITLE
Docs: truncate signature incorrect

### ISSUE THREAD

**Issue by watzon** [edge-js/edge#77]
## Package version
2.2.0

## Node.js and npm version
Node: v12.6.1
npm: 6.14.2

## Sample Code (to reproduce the issue)
```edge
truncate(text, 120, '...')
// should be
truncate(text, { length: 120, omission: '...' })
```

This is probably because the `truncate` global is using lodash under the hood, and the lodash signature may have changed. https://lodash.com/docs/#truncate

**Comment by thetutlage** [comment]
Fixed. Not using lodash anymore. Docs will be out for `v3.0.0` by the end of the week
