### ISSUE TITLE
How to use edge.js as standalone template engine?

### ISSUE THREAD

**Issue by monochromer** [edge-js/edge#80]
I found [documentation](https://edge.adonisjs.com/) but it seems outdated. 
These [docs](https://preview.adonisjs.com/guides/views/introduction) describe use only for _Adonis.js_. 
I want to use _edge.js_ for static site generator.

**Comment by thetutlage** [comment]
Yes, the docs for the standalone usage are not written. However, the `@adonisjs/view` provider can be used as a reference to instantiate a new edge instance. https://github.com/adonisjs/view/blob/develop/providers/ViewProvider.ts#L105

```ts
const { join } = require('path')
const { Edge } = require('edge.js')

const edge = new Edge({ cache: false })
edge.mount(join(__dirname, 'views'))

edge.render(viewPath, data)
```

**Comment by monochromer** [comment]
Thanks! Can I pass template string into render, not a path?

**Comment by thetutlage** [comment]
Covered in the docs already https://preview.adonisjs.com/guides/views/in-memory-views
