### ISSUE TITLE
One line conditional for dynamic classes?

### ISSUE THREAD

**Issue by ShabaniAmir** [edge-js/edge#82]
I'd like the current page to be styled differently in the nav bar links. I've tried passing the active page as I'm rendering them, i.e: `res.render('home', {active: "home"})`,
And in the nav bar I'd like to add a class to the link if active is set to 'home'.
The only thing I've come up with is: 
```
<a href="/" class="
                @if(active == 'home')
                active
                @endif
                ">Home</a>
```

And this does work well, but the rendered link results in the following, which isn't really pretty. 
```
<a href="/" class="
                  active

                  ">Home</a>
```

Are there any support for one line conditionals? I can also incorporate some js in the page to automatically add the class based on the URL but I'd like to keep it as simple as possible.

Thanks in advance.

**Comment by thetutlage** [comment]
Simply use the ternary operator inside the mustache braces

```
<a href="/" class="{{ active === 'home' ? 'active' : '' }}">Home</a>
```

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
