### ISSUE TITLE
Numeric `0` passed as `@!component()` agrument  becomes nothing in the component. Passing it as string goes fine.

### ISSUE THREAD

**Issue by WhereJuly** [edge-js/edge#83]
### ACTUAL BEHAVIOUR

1. I pass zero (in fact a $loop.index) into a component as follows and for a numeric `0` argument value I get the argument empty inside the component:

``` html
{{-- Calling the component --}}
<ul>
    @each(item in [
    {item: 'Item #:'},
    {item: 'Item #:'},
    {item: 'Item #:'},
    ])

    @!component('mycomponent', index = $loop.index)

    @endeach
</ul>

{{-- The component template --}}
<li>{{ index }}</li>


{{-- Outcome --}}
<li></li>
<li>1</li>
<li>2</li>
```

2. If I cast numeric `0` to string before passing to the component it goes fine, showing `0` in the component:

``` html
{{-- Transform 0 to string at --}}
@!component('mycomponent', index = $loop.index + '')

{{-- Outcome --}}
<li>0</li>
<li>1</li>
<li>2</li>
```

### Expected Behaviour

Probably passing numeric `0` to component should be kept as such within the component.

Though all in all the templating engine is just so great.

**Comment by thetutlage** [comment]
Which version of Edge are you using?

**Comment by WhereJuly** [comment]
@thetutlage Hi,

I am using it under AdonisJS `"@adonisjs/framework": "^5.0.9"` and I cannot see the Edge version in my `package.json`.

**Comment by thetutlage** [comment]
Sorry for the late reply. I just added a test for same and it seems to be working fine for me

**Comment by WhereJuly** [comment]
@thetutlage Thanks. I see. So far I have no time to check it again. I would close the issue but keep an eye on it. As soon as I approach another similar case I make another check and return here with what I find, if something.
